name: mppy
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scipy
  - jupyter
  - conda-forge::parmed
  - conda-forge::rdkit
  - conda-forge::mdanalysis
  - conda-forge::matplotlib
  - conda-forge::nglview
  
  
  