#!/bin/bash -l

# Batch script to run an MPI parallel job under SGE with Intel MPI.
# Request two hours of wallclock time (format hours:minutes:seconds).
#$ -l h_rt=24:00:00

# Request 1 gigabyte of RAM per process (must be an integer followed by M, G, or T)
#$ -l mem=1G

# Request 1 gigabyte of TMPDIR space per node
# (default is 10 GB - remove if cluster is diskless)
#$ -l tmpfs=2G

# Set the name of the job.
#$ -N job-name

# Select the MPI parallel environment and 36 processes.
#$ -pe mpi 36

# Set the working directory to somewhere in your scratch space.
#$ -cwd

# load gromacs
module unload gcc-libs
module unload mpi
module load gromacs/2021.3/plumed/gnu-10.2.0

export OMP_NUM_THREADS=1
gmx_mpi grompp -f md.mdp -o md.tpr -maxwarn 2 -p topol.top -c prev.gro -n index.ndx
gerun gmx_mpi mdrun -deffnm md -v


