#!/bin/bash -l

# Batch script to run an MPI parallel job under SGE with Intel MPI.

# Request two hours of wallclock time (format hours:minutes:seconds).
#$ -l h_rt=24:00:00

# Request 1 gigabyte of RAM per process (must be an integer followed by M, G, or T)
#$ -l mem=1G

# Request 1 gigabyte of TMPDIR space per node 
# (default is 10 GB - remove if cluster is diskless)
#$ -l tmpfs=2G

# Set the name of the job.
#$ -N MDjob

# Select the MPI parallel environment and 36 processes.
#$ -pe mpi 12

# Set the working directory to somewhere in your scratch space.
#$ -cwd 

# load gromacs
module unload -f compilers mpi
module load compilers/intel/2018/update3 mpi/intel/2018/update3/intel libmatheval flex plumed/2.5.2/intel-2018 gromacs/2019.3/plumed/intel-2018


